name             'promet_nginx'
maintainer       'gregpalmier'
maintainer_email 'gregpalmier@gmail.com'
license          'All rights reserved'
description      'Installs/Configures promet_nginx'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.1'
depends		 'apt'
depends		 'mysql'
depends		 'php'
depends		 'nginx'
